/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import Connect.DBConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author baonguyen
 * Manufacturer Management: Add new, Update, Delete
 */
public class JPanelManufacturer extends javax.swing.JPanel {

    /**
     * Creates new form JPanelManufacturer
     */
    
    // Private Properties
    private DefaultTableModel dtm = new DefaultTableModel(); // For Table
    Connection connect = DBConnection.getConnection();
    Statement statement;
    private int selectedId = -1;
    
    public JPanelManufacturer(){
        initComponents();
        try {
            statement = connect.createStatement();
        } catch (SQLException e) {
            
        }
        loadTable();
    }
    
    // Load Headers and row for Manufacturer Table
    private void loadTable(){
        // Headers
        String headers[] = {"Id", "Manufacturer Name"};
        
        // Set # of row to 0
        dtm.setRowCount(0);
        dtm.setColumnIdentifiers(headers);
        this.jTableManufacturer.setModel(dtm);
        try {
            ResultSet rs = statement.executeQuery("Select * from Manufacturer");
            while (rs.next()) {
                dtm.addRow(new Object[]{rs.getInt(1), rs.getString(2)});
            }
        } catch (SQLException e) {
            
        } 
    }
    
    // Reset the textfiled and load table
    private void reset(){
        this.jTextFieldId.setText("");
        this.jTextFieldManufacturerName.setText("");
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelManufacturerList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableManufacturer = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldManufacturerName = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanelManufacturerList.setBackground(new java.awt.Color(255, 255, 255));
        jPanelManufacturerList.setBorder(javax.swing.BorderFactory.createTitledBorder("Manufacturer List"));
        jPanelManufacturerList.setToolTipText("Manufacturer List");
        jPanelManufacturerList.setName("Manufacturer List"); // NOI18N

        jTableManufacturer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableManufacturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableManufacturerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableManufacturer);

        javax.swing.GroupLayout jPanelManufacturerListLayout = new javax.swing.GroupLayout(jPanelManufacturerList);
        jPanelManufacturerList.setLayout(jPanelManufacturerListLayout);
        jPanelManufacturerListLayout.setHorizontalGroup(
            jPanelManufacturerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManufacturerListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelManufacturerListLayout.setVerticalGroup(
            jPanelManufacturerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManufacturerListLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Manufacture Detail"));

        jLabel1.setText("Id");

        jLabel2.setText("Manufacturer Name");

        jTextFieldId.setEnabled(false);
        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        jTextFieldManufacturerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldManufacturerNameActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldId)
                        .addComponent(jTextFieldManufacturerName, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldManufacturerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelManufacturerList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelManufacturerList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelManufacturerList.getAccessibleContext().setAccessibleName("Manufacturer List");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldManufacturerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldManufacturerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldManufacturerNameActionPerformed
    
    // Handle event when user click on table
    private void jTableManufacturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableManufacturerMouseClicked
        // TODO add your handling code here:
        int row = this.jTableManufacturer.getSelectedRow();
        selectedId = (Integer) this.jTableManufacturer.getValueAt(row, 0);
        this.jTextFieldId.setText(this.jTableManufacturer.getValueAt(row, 0).toString());
        this.jTextFieldManufacturerName.setText(this.jTableManufacturer.getValueAt(row, 1).toString());
        
    }//GEN-LAST:event_jTableManufacturerMouseClicked

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed
    
    
    // Update Manufacturer
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        if(this.jTableManufacturer.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Choose a manufacturer to moldify");
        } else {
            try {
                statement.executeUpdate("update Manufacturer set name = '" +
                        this.jTextFieldManufacturerName.getText() + "' where mid = " + selectedId);
               
                JOptionPane.showMessageDialog(null, "Update Succeded");
                reset();
            } catch (SQLException e) {
                //String updateString = "upadte Manufacturer set name = ? where mid = ?";
                System.out.println(e.getErrorCode());
                JOptionPane.showMessageDialog(null, "Update Failed");
                
                
            }
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
         if(this.jTableManufacturer.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Choose a manufacturer to delete");
        } else {
            try {
                
                statement.executeUpdate("delete from Manufacturer where mid = " + selectedId);
               
                JOptionPane.showMessageDialog(null, "Delete Succeded");
                reset();
            } catch (SQLException e) {
                //String updateString = "upadte Manufacturer set name = ? where mid = ?";
                System.out.println(e.getErrorCode());
                JOptionPane.showMessageDialog(null, "Detele Failed");
                
                
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        try {
                
                statement.executeUpdate("insert into Manufacturer(name) values ('" + 
                        this.jTextFieldManufacturerName.getText() + "')");
               
                JOptionPane.showMessageDialog(null, "Add Manufacturer Succeded");
                reset();
            } catch (SQLException e) {
                //String updateString = "upadte Manufacturer set name = ? where mid = ?";
                System.out.println(e.getErrorCode());
                JOptionPane.showMessageDialog(null, "Add Manufacturer Failed");             
            }
    }//GEN-LAST:event_jButtonAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelManufacturerList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableManufacturer;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldManufacturerName;
    // End of variables declaration//GEN-END:variables
}
